name: handobject_env
channels:
  - menpo
  - pytorch
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - cupy
  - joblib
  - opencv
  - pandas
  - python=3.7
  - pyyaml
  - matplotlib
  - moviepy
  - numpy
  - pillow
  - pytorch=1.4
  - scikit-image
  - torchvision
  - trimesh
  - tqdm
  - cupy
  - pip
  - plotly
  - pythreejs
  - pip:
    - chumpy
    - kornia==0.2
    - opencv-python
    - git+https://github.com/hassony2/manopth.git
    - git+https://github.com/hassony2/libyana@v0.1.0
    - neural-renderer-pytorch
